# https://pre-commit.com
# This GitHub Action assumes that the repo contains a valid .pre-commit-config.yaml file.
name: pre-commit
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

  pull_request:
  push:
    branches: [main]
    paths:
      - "*.py"

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python -m pip install pre-commit
      - run: python -m pre_commit --version
      - run: python -m pre_commit install
      - run: python -m pre_commit run --all-files
